blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/AleksaZatezalo/GrapeQL/security/advisories/new
    about: Please report security vulnerabilities through GitHub's private security advisory feature
  - name: GitHub Discussions
    url: https://github.com/AleksaZatezalo/GrapeQL/discussions
    about: Ask questions and discuss ideas with the community