name: Documentation Issue
description: Report an issue with documentation or suggest documentation improvements
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - README
        - API Documentation
        - Code Comments
        - Examples
        - Installation Instructions
        - CLI Help Text
        - Other
    validations:
      required: true

  - type: textarea
    id: current-docs
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (copy/paste or link)

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: Is it unclear, outdated, incorrect, or missing?
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful