name: Security Vulnerability
description: Report a security vulnerability (USE PRIVATE SECURITY ADVISORIES INSTEAD)
title: "[Security]: "
labels: ["security", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **STOP**: For security vulnerabilities, please use GitHub's private security advisory feature instead of public issues.
        
        Go to: Repository → Security → Report a vulnerability
        
        If you must use this template, please provide minimal details and we will reach out privately.

  - type: textarea
    id: minimal-description
    attributes:
      label: Minimal Description
      description: Very brief description of the issue type (no specific details)
      placeholder: "e.g., 'Potential authentication bypass' or 'Possible injection vulnerability'"
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: How can we reach you privately to discuss this?
      placeholder: email@example.com
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        We will respond to security reports within 48 hours. Thank you for responsible disclosure!